### ISSUE TITLE
why msedge-stable The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by candrapersada** [42wim/scoop-bucket#10]
Installing 'msedge-stable' (95.0.1020.40) [64bit]
The remote server returned an error: (403) Forbidden.
URL `http://msedge.f.tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/b3ff5936-b1f1-4bd2-a9a5-b8f32b7c9992?P1=1636169575&P2=404&P3=2&P4=GD8SWUhMjG7GhnPfApg9hLOzThYNanjrIJIlmNLkVZtSU6E60gojnh17DBYYsyW1ccqjx661hq6ocfidEOgBdw%3d%3dbA%3d%3ddd%3d#/dl.7z` is not valid

**Comment by 42wim** [comment]
It worked for me (just tested), if it stops working, this isn't something I can fix as microsoft can disable the links when they want

**Comment by candrapersada** [comment]
but the problem happened to my ip
103.105.78.129 indonesia
