### ISSUE TITLE
googlechrome@88.0.4324.190: Resource was not found

### ISSUE THREAD

**Issue by RavenMacDaddy** [42wim/scoop-bucket#2]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://dl.google.com/release2/chrome/XbbQJbJsaeK1V9RebtMbuA_88.0.4324.190/88.0.4324.190_chrome_installer.exe#/dl.7z
    referer=https://dl.google.com/release2/chrome/XbbQJbJsaeK1V9RebtMbuA_88.0.4324.190/88.0.4324.190_chrome_installer.exe#/
    dir=C:\users\amand\Scoop\cache
    out=googlechrome#88.0.4324.190#https_dl.google.com_release2_chrome_XbbQJbJsaeK1V9RebtMbuA_88.0.4324.190_88.0.4324.190_chrome_installer.exe_dl.7z

ERROR & 'C:\users\amand\Scoop\apps\aria2\current\aria2c.exe' --input-file='C:\users\amand\Scoop\cache\googlechrome.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=8368 --continue --summary-interval 0
ERROR Download failed! (Error 3) Resource was not found

**Comment by 42wim** [comment]
should be fixed now btw, google changd their urls
